version: '3.8'

services:
  postgres:
    container_name: nestjs-authentication
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs-authentication
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
